### ISSUE TITLE
SSM not applying ENV in rails console

### ISSUE THREAD

**Issue by christianbradley** [atomaka/psenv#13]
Running latest Rails (6.x)

If I run `rails console`, the ENV vars are not applied from SSM. Seems to load OK when running `rails server`.

Here's my `application.rb` (first lines)

```ruby
require_relative 'boot'

require "rails"
require 'psenv-rails'
```

**Comment by atomaka** [comment]
I'm having trouble replicating this:

```
|-> PARAMETER_STORE_PATH=/psenv/test/ bundle exec rails console
Loading development environment (Rails 6.0.0)
irb(main):001:0> ENV['API_KEY']
=> "api_key_value"
```

It might be an issue with require order. I am testing using the sample app in https://github.com/atomaka/psenv/tree/master/spec/rails which does not explicitly load the `psenv-rails` gem and instead relies on bundler to do it.

**Comment by atomaka** [comment]
@christianbradley Any chance you're using the spring application preloader?  I have seen this issue with the spring gem:

```
|-> bundle exec rails console
Running via Spring preloader in process 91069
Loading development environment (Rails 6.0.0)
irb(main):001:0> ENV.fetch('API_KEY') # not here since PARAMETER_STORE_PATH not provided
Traceback (most recent call last):
        2: from (irb):1
        1: from (irb):1:in `fetch'
KeyError (key not found: "API_KEY")
irb(main):002:0> exit
|-> PARAMETER_STORE_PATH=/psenv/test/ bundle exec rails console
Running via Spring preloader in process 91126
Loading development environment (Rails 6.0.0)
irb(main):001:0> ENV.fetch('API_KEY') # expected to be found, but isn't
Traceback (most recent call last):
        2: from (irb):1
        1: from (irb):1:in `fetch'
KeyError (key not found: "API_KEY")
irb(main):002:0> exit
|-> bin/spring stop
Spring stopped.
[09:29:39] andrew.tomaka@MBP-62.local ~/Source/psenv/spec/rails [master]
|-> PARAMETER_STORE_PATH=/psenv/test/ bundle exec rails console
Running via Spring preloader in process 91269
Loading development environment (Rails 6.0.0)
irb(main):001:0> ENV.fetch('API_KEY') # now available since we restarted spring
=> "api_key_value"
```

**Comment by atomaka** [comment]
https://github.com/rails/spring/issues/420 and https://github.com/rails/spring/issues/490 appear to be relevant but unresolved issues.

Can you try using `bundle exec spring stop` and then loading the console (making sure to load `PARAMETER_STORE_PATH` before running any rails command either inline with the command or via `export`?

**Comment by atomaka** [comment]
Feel free to pop a comment in here if the suggested fix doesn't fix anything for you!
